# Generated by Django 5.1.1 on 2024-09-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskHistoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('task', models.CharField(max_length=255)),
                ('updated_by', models.CharField(max_length=255)),
                ('progress', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
